# Generated by Django 5.2.1 on 2025-05-28 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('especialidad', models.CharField(max_length=255, verbose_name='Especialidad')),
                ('numero_colegiado', models.CharField(max_length=20, unique=True, verbose_name='Número de Colegiado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='psicologos/', verbose_name='Foto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Psicólogo',
                'verbose_name_plural': 'Psicólogos',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
    ]
